# Generated by Django 4.0.5 on 2022-08-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0005_hilo_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='receptor',
            new_name='receptor_user',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='remitente',
            new_name='remitente_user',
        ),
    ]
